# This file defines parameters specific to Beluga
#
# When looking at the AUV from above, the thruster placement is:   

# Parameters that will be used in the guidance, navigation and control system.

model_parameters:
  mass: 28 # kg
  volume: 0.0272 # m^3
  center_of_mass: [0, 0, -0.094] # w.r.t. ENU
  center_of_buoyancy: [0, 0, 0.035] # w.r.t. ENU
  inertia: # Inertia about center of mass
    [[ 0.5, 0, 0],
     [ 0, 0.5, 0],
     [ 0, 0, 0.92]]
  water_density: 1028
  M_A: [20, 40, 50, 0.5, 2, 2] # Added mass
  D: [-20, -40, -50, -3, -10, -12] # Linear damping

thruster_parameters:
  first_order_time_constant: 0.2
  rotor_constant: 0.00000364
  positions: # w.r.t. ENU
    [[  0.238, -0.220,  0.065],
     [  0.120, -0.220,  0.065],
     [ -0.120, -0.220,  0.065],
     [ -0.240, -0.220,  0.065],
     [ -0.240,  0.220,  0.065],
     [ -0.120,  0.220,  0.065],
     [  0.120,  0.220,  0.065],
     [  0.238,  0.220,  0.065]]
  orientations: # w.r.t. ENU
    [[ 0,      0, -2.356],
     [ 0, -1.571,      0],
     [ 0, -1.571,      0],
     [ 0,      0, -0.785],
     [ 0,      0,  0.785],
     [ 0, -1.571,      0],
     [ 0, -1.571,      0],
     [ 0,      0,  2.356]]

guidance_and_control_parameters:
  sphere_of_acceptence: 0.1
  control_input_saturation_limits: [-10.5, 10.5]
  control_forces_weights: [0.1, 0.1, 0.1, 10, 10, 1] # Weigths for what DOF is prioritized when allocation control forces. Leave 
  control_bandwidth: [0.4, 0.4, 0.4, 0.4, 0.4, 0.4 ]   # Tune the PID control bandwidths for [surge, sway, heave, roll, pitch, yaw]. NB! roll and pitch are redundant
  relative_damping_ratio: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0] # Leave
  absolute_relative_velocity_limit: 0.5 # Leave
  reference_model_control_bandwidth_gain: 0.5 # <= 1 # Leave 
  reference_model_control_input_saturation_limit_gain: 0.8 # <= 1 Leave
  virtual_target_controller_bandwidths: [0.75, 0.75, 0.75, 1, 1, 1.5]  # Tune the path following precision for [surge, sway, heave, roll, pitch, yaw]  NB! roll and pitch are redundant. Higher values gives better precision
  virtual_target_along_track_speed_saturation_limits: [-0.2, 0.2] # <= 1 Speed saturation limits for the virtual target along the path
  virtual_target_control_input_saturation_limit_gain: 0.8 # <= 1 Leave
  publish_rate: 20 # The node frequency




 



  
