name: black-format check

on: [ push ]

jobs:
  linter_name:
    name: runner / black formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jpetrucciani/black-check@21.12b0
        with:
          path: "."
          black_flags: "--check"
